title: "Ali's Portfolio"
email: "aaliyev.work@gmail.com"
baseurl: "" # the subpath of your site on GitHub Pages
url: "https://alialiyev-git.github.io" # the base hostname & protocol for your site
source: src # source directory for Jekyll files
markdown: kramdown
